apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  namespace: jenkins
  labels: 
    run: jenkins
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0 
  containers:
  - name: jenkins-container
    image: mohamedsambo/customized-jenkins:v1
    resources:
      limits:
        memory: "4Gi"
        cpu: "1000m"
      requests:
        memory: "500Mi"
        cpu: "500m"
    ports:
      - name: http-port
        containerPort: 8080
      - name: jnlp-port
        containerPort: 5000
    # env:
    #   - name: CASC_JENKINS_CONFIG
    #     value: /var/jenkins_conf/jenkins.yaml
    volumeMounts:
     # - name: jenkins-conf
     #   mountPath: /var/jenkins_conf
      - name: jenkins-data
        mountPath: /var/jenkins_home
  volumes:
    # - name: jenkins-conf
    #   hostPath:
    #     path:  /data
    #     type: DirectoryOrCreate
    - name: jenkins-data
      persistentVolumeClaim:
        claimName: jenkins-pv-claim



      
